using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TicketCentral.Infrastructure.Data;
using TicketCentral.Infrastructure.Models;
using TicketCentral.Modules.TicketOrders.DTOs;
using TicketCentral.Modules.Payments.Services;


namespace TicketCentral.Modules.Tickets.Controllers;


[ApiController]
[Route("api/v1/[controller]")]
public class TicketOrdersController : ControllerBase
{
    private readonly AppDbContext _dbContext;
    private readonly RelworxPaymentService _paymentService;

    private readonly ILogger<TicketOrdersController> _logger;


    public TicketOrdersController(
        AppDbContext dbContext,
            RelworxPaymentService paymentService,
        ILogger<TicketOrdersController> logger)
    {
        _dbContext = dbContext;
        _paymentService = paymentService;
        _logger = logger;
    }



    // ---------------- CREATE ORDER ----------------
    [HttpPost]
    public async Task<IActionResult> CreateOrder(
        CreateTicketOrderDto request)
    {
        try
        {
            var ticketType =
                await _dbContext.TicketTypes
                .FirstOrDefaultAsync(x =>
                    x.Id == request.TicketTypeId);

            if (ticketType == null)
                return NotFound("Ticket type not found");


            if (ticketType.TotalNumberLeft < request.Quantity)
                return BadRequest("Not enough tickets available");


            var eventItem =
                await _dbContext.Events
                .FirstOrDefaultAsync(x =>
                    x.Id == request.EventId);


            if (eventItem == null)
                return NotFound("Event not found");


            var amount = ticketType.Price * request.Quantity;


            var paymentReference =
                Guid.NewGuid()
                .ToString()
                .Replace("-", "")
                .Substring(0, 20);


            var paymentResponse =
                await _paymentService.RequestPayment(
                    request.Phone,
                    amount,
                    paymentReference);


            if (paymentResponse == null ||
                !paymentResponse.Success)
            {
                return BadRequest(new
                {
                    message = "Payment request failed"
                });
            }


            var ticketOrder = new TicketOrder
            {
                Id = Guid.NewGuid(),

                UserId = request.UserId,

                EventId = request.EventId,

                TicketTypeId = request.TicketTypeId,


                FirstName = request.FirstName,
                LastName = request.LastName,
                Email = request.Email,
                Phone = request.Phone,


                Quantity = request.Quantity,


                PaymentMethod = request.PaymentMethod,

                UserPaysBookingFee =
                    request.UserPaysBookingFee,


                QRCode = Guid.NewGuid()
                    .ToString(),


                IsPaid = false,

                IsScanned = false,


                OrganiserDividend = 0,

                PlatformDividend = 0,


                // Generated by system
                PaymentReference = paymentReference,


                // Returned by Relworx
                ProviderReference =
                    paymentResponse.Internal_reference,


                CreatedAt = DateTime.UtcNow
            };


            ticketType.TotalNumberLeft -= request.Quantity;


            if (ticketType.TotalNumberLeft == 0)
            {
                ticketType.IsActive = false;
            }


            _dbContext.TicketOrders.Add(ticketOrder);


            await _dbContext.SaveChangesAsync();


            return CreatedAtAction(
                nameof(GetOrder),
                new
                {
                    id = ticketOrder.Id
                },
                new
                {
                    message = "Payment request initiated",
                    orderId = ticketOrder.Id,
                    paymentReference =
                        ticketOrder.PaymentReference,
                    providerReference =
                        ticketOrder.ProviderReference
                });
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Error creating ticket order");

            return StatusCode(
                500,
                "Internal server error");
        }
    }



    // ---------------------GET ALL ORDERS---------------------------

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> GetOrders()
    {
        var orders =
            await _dbContext.TicketOrders
            .OrderByDescending(x => x.CreatedAt)
            .ToListAsync();


        return Ok(orders);
    }


    //----------------------GET ORDER BY ID---------------------

    [HttpGet("{id:guid}")]
    public async Task<IActionResult> GetOrder(Guid id)
    {

        var order =
            await _dbContext.TicketOrders
            .FirstOrDefaultAsync(x => x.Id == id);


        if (order == null)
            return NotFound("Order not found");


        return Ok(order);
    }



    // ---------------- GET MY ORDERS ----------------
    [Authorize]
    [HttpGet("myTicketOrders")]
    public async Task<IActionResult> GetUserOrders()
    {
        try
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;


            if (string.IsNullOrEmpty(userIdClaim))
                return Unauthorized("Invalid token");


            var userId = Guid.Parse(userIdClaim);


            var orders = await _dbContext.TicketOrders
                .Where(x => x.UserId == userId)
                .OrderByDescending(x => x.CreatedAt)
                .ToListAsync();

            return Ok(orders);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching user orders");

            return StatusCode(500, "Internal server error");
        }
    }



    //----------------GET EVENT ORDERS--------------

    [HttpGet("event/{eventId:guid}")]
    public async Task<IActionResult> GetEventOrders(
        Guid eventId)
    {

        var orders =
            await _dbContext.TicketOrders
            .Where(x => x.EventId == eventId)
            .ToListAsync();


        return Ok(orders);
    }


    //----------------PAYMENT CALLBACK--------------------

    [HttpPost("payment-callback")]
    public async Task<IActionResult> PaymentCallback(
        PaymentCallbackDto request)
    {

        var order =
            await _dbContext.TicketOrders
            .FirstOrDefaultAsync(x =>
                x.Id == request.TicketOrderId);


        if (order == null)
            return NotFound();


        if (request.Status == "success")
        {
            order.IsPaid = true;

            order.PaymentReference =
                request.TransactionReference;


            // Example split
            order.PlatformDividend =
                request.Amount * 0.05m;


            order.OrganiserDividend =
                request.Amount -
                order.PlatformDividend;
        }


        await _dbContext.SaveChangesAsync();


        return Ok(new
        {
            message = "Payment updated"
        });
    }



    // -----------------VERIFY QR CODE-----------------

    [HttpPost("verify")]
    public async Task<IActionResult> VerifyTicket(
        VerifyTicketDto request)
    {

        var ticket =
            await _dbContext.TicketOrders
            .FirstOrDefaultAsync(x =>
                x.QRCode == request.QRCode);



        if (ticket == null)
            return NotFound("Invalid ticket");



        if (!ticket.IsPaid)
            return BadRequest("Ticket not paid");



        if (ticket.IsScanned)
            return BadRequest("Ticket already used");



        ticket.IsScanned = true;

        ticket.EditedAt = DateTime.UtcNow;


        await _dbContext.SaveChangesAsync();



        return Ok(new
        {
            message = "Ticket verified successfully",
            ticketId = ticket.Id
        });
    }



    // -----------------DELETE ORDER-----------------
    [Authorize]
    [HttpDelete("{id:guid}")]
    public async Task<IActionResult> DeleteOrder(
        Guid id)
    {

        var order =
            await _dbContext.TicketOrders
            .FindAsync(id);


        if (order == null)
            return NotFound();



        _dbContext.TicketOrders.Remove(order);


        await _dbContext.SaveChangesAsync();


        return Ok("Order deleted");
    }


}